### ISSUE TITLE
Website seems to be down?????

### ISSUE THREAD

**Issue by therealtenndex** [VaporousCreeper/TheBox-Sound-files#2]
**Website appears to be down, either oof.wav is not loading on boot, or your version of Antchat3 has become corrupted.

thank you, and god bless you on your journey**

**Comment by BradF-99** [comment]
I seem to get the same issue where the website and issue #1 is down for maintenance as well.

**Comment by VaporousCreeper** [comment]
This repository has nothing to do with the website
